# Generated by Django 4.2.7 on 2025-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sweets/'),
        ),
    ]
